# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
